// Question bank: Python + SQL, basics -> real interview questions
// Each question: id, cat (python/sql), phase (basics/interview), difficulty, title, prompt, solution, explain
// `day` is assigned programmatically below so the schedule always fits Jul 8 - Aug 8.

const pythonBasics = [
  {id:'pyb1', cat:'python', difficulty:'Easy', title:'Reverse a string',
   prompt:'Write a function reverse_str(s) that returns the string reversed, without using s[::-1].',
   solution:'def reverse_str(s):\n    result = ""\n    for ch in s:\n        result = ch + result\n    return result',
   explain:'Slicing is the idiomatic one-liner, but interviewers often ask you to do it manually to check loop logic.'},
  {id:'pyb2', cat:'python', difficulty:'Easy', title:'Check palindrome',
   prompt:'Write is_palindrome(s) that returns True if s reads the same forwards and backwards (case-insensitive).',
   solution:'def is_palindrome(s):\n    s = s.lower()\n    return s == s[::-1]',
   explain:'Normalize case first. Follow-up: ignore non-alphanumeric chars (see interview version later).'},
  {id:'pyb3', cat:'python', difficulty:'Easy', title:'FizzBuzz',
   prompt:'Print numbers 1 to n. Multiples of 3 -> "Fizz", multiples of 5 -> "Buzz", multiples of both -> "FizzBuzz".',
   solution:'def fizzbuzz(n):\n    for i in range(1, n+1):\n        if i % 15 == 0: print("FizzBuzz")\n        elif i % 3 == 0: print("Fizz")\n        elif i % 5 == 0: print("Buzz")\n        else: print(i)',
   explain:'Check the combined condition (15) first, otherwise Fizz/Buzz will fire before FizzBuzz can.'},
  {id:'pyb4', cat:'python', difficulty:'Easy', title:'Find max without max()',
   prompt:'Write find_max(nums) that returns the largest number in a non-empty list without using max().',
   solution:'def find_max(nums):\n    best = nums[0]\n    for n in nums[1:]:\n        if n > best:\n            best = n\n    return best',
   explain:'Classic "implement the builtin yourself" warm-up question.'},
  {id:'pyb5', cat:'python', difficulty:'Easy', title:'Count vowels',
   prompt:'Write count_vowels(s) that returns how many vowels (a,e,i,o,u, case-insensitive) are in s.',
   solution:'def count_vowels(s):\n    return sum(1 for ch in s.lower() if ch in "aeiou")',
   explain:'Generator expression inside sum() is a common Pythonic pattern worth being fluent in.'},
  {id:'pyb6', cat:'python', difficulty:'Easy', title:'Remove duplicates, keep order',
   prompt:'Write dedupe(lst) that removes duplicates from a list while preserving the original order.',
   solution:'def dedupe(lst):\n    seen = set()\n    result = []\n    for x in lst:\n        if x not in seen:\n            seen.add(x)\n            result.append(x)\n    return result',
   explain:'set(lst) removes dupes but loses order — this seen-set pattern shows up constantly in interviews.'},
  {id:'pyb7', cat:'python', difficulty:'Easy', title:'Sum of digits',
   prompt:'Write digit_sum(n) that returns the sum of the digits of a positive integer n.',
   solution:'def digit_sum(n):\n    total = 0\n    while n > 0:\n        total += n % 10\n        n //= 10\n    return total',
   explain:'The %10 / //10 combo is the standard way to peel off digits without converting to a string.'},
  {id:'pyb8', cat:'python', difficulty:'Easy', title:'Check prime',
   prompt:'Write is_prime(n) that returns True if n is a prime number.',
   solution:'def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n**0.5)+1):\n        if n % i == 0:\n            return False\n    return True',
   explain:'Only check divisors up to sqrt(n) — a very common efficiency follow-up question.'},
  {id:'pyb9', cat:'python', difficulty:'Easy', title:'Fibonacci sequence',
   prompt:'Write fib(n) that returns a list of the first n Fibonacci numbers, starting 0, 1, 1, 2, 3...',
   solution:'def fib(n):\n    seq = [0, 1]\n    while len(seq) < n:\n        seq.append(seq[-1] + seq[-2])\n    return seq[:n]',
   explain:'Recursive fib is elegant but O(2^n) — mention memoization/DP if asked to optimize.'},
  {id:'pyb10', cat:'python', difficulty:'Easy', title:'Merge two dictionaries',
   prompt:'Write merge_dicts(a, b) that merges two dicts; keys in b overwrite keys in a.',
   solution:'def merge_dicts(a, b):\n    return {**a, **b}',
   explain:'Python 3.9+ also supports a | b. Know both since interviewers may ask for the older syntax.'},
  {id:'pyb11', cat:'python', difficulty:'Easy', title:'Word frequency counter',
   prompt:'Write word_freq(sentence) that returns a dict mapping each word (lowercased) to its count.',
   solution:'from collections import Counter\ndef word_freq(sentence):\n    return dict(Counter(sentence.lower().split()))',
   explain:'Counter is the go-to tool for frequency problems — expect it to reappear in real interview questions.'},
  {id:'pyb12', cat:'python', difficulty:'Easy', title:'Squares of even numbers',
   prompt:'Using a list comprehension, return the squares of all even numbers in a list nums.',
   solution:'def even_squares(nums):\n    return [n*n for n in nums if n % 2 == 0]',
   explain:'List comprehensions with a filter clause are extremely common in Python interviews.'},
  {id:'pyb13', cat:'python', difficulty:'Easy', title:'Swap two variables',
   prompt:'Show how to swap the values of a and b without using a temporary variable.',
   solution:'a, b = b, a',
   explain:'Python tuple unpacking makes this trivial — know why other languages need a temp variable.'},
  {id:'pyb14', cat:'python', difficulty:'Easy', title:'Flatten a nested list (one level)',
   prompt:'Write flatten(lst) that flattens a list of lists by one level, e.g. [[1,2],[3],[4,5]] -> [1,2,3,4,5].',
   solution:'def flatten(lst):\n    result = []\n    for sub in lst:\n        result.extend(sub)\n    return result',
   explain:'extend() vs append() is a common point of confusion — extend adds elements, append adds the whole sublist.'},
  {id:'pyb15', cat:'python', difficulty:'Easy', title:'Title case each word',
   prompt:'Write title_case(s) that capitalizes the first letter of every word in a sentence, without using str.title().',
   solution:'def title_case(s):\n    return " ".join(w[0].upper() + w[1:] if w else w for w in s.split())',
   explain:'str.title() breaks on apostrophes (e.g. "don\'t" -> "Don\'T"), so knowing the manual version matters.'},
];

const pythonInterview = [
  {id:'pyi1', cat:'python', difficulty:'Easy', title:'Two Sum',
   prompt:'Given a list of integers nums and a target, return the indices of the two numbers that add up to target. Assume exactly one solution.\nExample: nums=[2,7,11,15], target=9 -> [0,1]',
   solution:'def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        complement = target - n\n        if complement in seen:\n            return [seen[complement], i]\n        seen[n] = i',
   explain:'Hash map gives O(n) instead of the brute-force O(n^2) double loop — the single most-asked interview question.'},
  {id:'pyi2', cat:'python', difficulty:'Easy', title:'Valid Anagram',
   prompt:'Given two strings s and t, return True if t is an anagram of s.\nExample: s="anagram", t="nagaram" -> True',
   solution:'from collections import Counter\ndef is_anagram(s, t):\n    return Counter(s) == Counter(t)',
   explain:'Counter comparison handles this in one line; alternative is sorting both strings and comparing.'},
  {id:'pyi3', cat:'python', difficulty:'Easy', title:'Contains Duplicate',
   prompt:'Given a list nums, return True if any value appears at least twice.',
   solution:'def contains_duplicate(nums):\n    return len(nums) != len(set(nums))',
   explain:'Comparing lengths after converting to a set is O(n) and very idiomatic.'},
  {id:'pyi4', cat:'python', difficulty:'Easy', title:'Best Time to Buy and Sell Stock',
   prompt:'Given daily prices, return the max profit from buying then selling once (buy before sell).\nExample: [7,1,5,3,6,4] -> 5 (buy at 1, sell at 6)',
   solution:'def max_profit(prices):\n    min_price = float("inf")\n    best = 0\n    for p in prices:\n        min_price = min(min_price, p)\n        best = max(best, p - min_price)\n    return best',
   explain:'Track the minimum price seen so far in a single pass — O(n) time, O(1) space.'},
  {id:'pyi5', cat:'python', difficulty:'Medium', title:'Group Anagrams',
   prompt:'Group a list of strings into anagram groups.\nExample: ["eat","tea","tan","ate","nat","bat"] -> [["eat","tea","ate"],["tan","nat"],["bat"]]',
   solution:'from collections import defaultdict\ndef group_anagrams(strs):\n    groups = defaultdict(list)\n    for s in strs:\n        key = "".join(sorted(s))\n        groups[key].append(s)\n    return list(groups.values())',
   explain:'Sorted string as a dict key is the standard trick — anagrams always sort to the same key.'},
  {id:'pyi6', cat:'python', difficulty:'Easy', title:'Valid Parentheses',
   prompt:'Given a string of brackets ()[]{}, return True if the brackets are balanced and correctly nested.',
   solution:'def is_valid(s):\n    stack = []\n    pairs = {")":"(", "]":"[", "}":"{"}\n    for ch in s:\n        if ch in pairs.values():\n            stack.append(ch)\n        elif ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n    return not stack',
   explain:'Stack is the natural data structure for matching nested pairs — a very frequent interview pattern.'},
  {id:'pyi7', cat:'python', difficulty:'Medium', title:'Merge Intervals',
   prompt:'Given a list of intervals [[start,end],...], merge all overlapping intervals.\nExample: [[1,3],[2,6],[8,10]] -> [[1,6],[8,10]]',
   solution:'def merge(intervals):\n    intervals.sort(key=lambda x: x[0])\n    result = [intervals[0]]\n    for start, end in intervals[1:]:\n        if start <= result[-1][1]:\n            result[-1][1] = max(result[-1][1], end)\n        else:\n            result.append([start, end])\n    return result',
   explain:'Sort by start time first, then a single pass — sorting turns an O(n^2) comparison problem into O(n log n).'},
  {id:'pyi8', cat:'python', difficulty:'Medium', title:'Longest Substring Without Repeating Characters',
   prompt:'Given a string s, find the length of the longest substring without repeating characters.\nExample: "abcabcbb" -> 3 ("abc")',
   solution:'def length_of_longest_substring(s):\n    seen = {}\n    left = 0\n    best = 0\n    for right, ch in enumerate(s):\n        if ch in seen and seen[ch] >= left:\n            left = seen[ch] + 1\n        seen[ch] = right\n        best = max(best, right - left + 1)\n    return best',
   explain:'Sliding window with a hash map of last-seen index is the standard O(n) solution.'},
  {id:'pyi9', cat:'python', difficulty:'Medium', title:'Top K Frequent Elements',
   prompt:'Given nums and k, return the k most frequent elements.\nExample: nums=[1,1,1,2,2,3], k=2 -> [1,2]',
   solution:'from collections import Counter\ndef top_k_frequent(nums, k):\n    return [item for item, _ in Counter(nums).most_common(k)]',
   explain:'Counter.most_common(k) does the heavy lifting; know the manual heap-based O(n log k) version as a follow-up.'},
  {id:'pyi10', cat:'python', difficulty:'Medium', title:'Product of Array Except Self',
   prompt:'Given nums, return an array where output[i] = product of all elements except nums[i], without using division.\nExample: [1,2,3,4] -> [24,12,8,6]',
   solution:'def product_except_self(nums):\n    n = len(nums)\n    result = [1] * n\n    left = 1\n    for i in range(n):\n        result[i] = left\n        left *= nums[i]\n    right = 1\n    for i in range(n-1, -1, -1):\n        result[i] *= right\n        right *= nums[i]\n    return result',
   explain:'Two passes: prefix products left-to-right, then multiply in suffix products right-to-left. O(n), no division.'},
  {id:'pyi11', cat:'python', difficulty:'Easy', title:'Move Zeroes',
   prompt:'Given nums, move all zeroes to the end while keeping the relative order of non-zero elements, in-place.\nExample: [0,1,0,3,12] -> [1,3,12,0,0]',
   solution:'def move_zeroes(nums):\n    pos = 0\n    for i in range(len(nums)):\n        if nums[i] != 0:\n            nums[pos], nums[i] = nums[i], nums[pos]\n            pos += 1\n    return nums',
   explain:'Two-pointer in-place swap — a common "modify array without extra space" pattern.'},
  {id:'pyi12', cat:'python', difficulty:'Easy', title:'Valid Palindrome (ignore non-alnum)',
   prompt:'Given a string, return True if it is a palindrome considering only alphanumeric characters and ignoring case.\nExample: "A man, a plan, a canal: Panama" -> True',
   solution:'def is_palindrome(s):\n    cleaned = [c.lower() for c in s if c.isalnum()]\n    return cleaned == cleaned[::-1]',
   explain:'Filter first with isalnum(), then compare to its reverse — cleaner than a two-pointer scan for most interviews.'},
  {id:'pyi13', cat:'python', difficulty:'Easy', title:'Longest Common Prefix',
   prompt:'Given a list of strings, find the longest common prefix among all of them.\nExample: ["flower","flow","flight"] -> "fl"',
   solution:'def longest_common_prefix(strs):\n    if not strs:\n        return ""\n    prefix = strs[0]\n    for s in strs[1:]:\n        while not s.startswith(prefix):\n            prefix = prefix[:-1]\n    return prefix',
   explain:'Shrink the prefix one character at a time until every string starts with it.'},
  {id:'pyi14', cat:'python', difficulty:'Medium', title:'Two Sum II (sorted array)',
   prompt:'Given a sorted list numbers and a target, return 1-indexed positions of two numbers that add up to target, using O(1) extra space.\nExample: [2,7,11,15], target=9 -> [1,2]',
   solution:'def two_sum_sorted(numbers, target):\n    left, right = 0, len(numbers) - 1\n    while left < right:\n        s = numbers[left] + numbers[right]\n        if s == target:\n            return [left + 1, right + 1]\n        elif s < target:\n            left += 1\n        else:\n            right -= 1',
   explain:'Since the array is sorted, two pointers converging from both ends beats a hash map on space.'},
  {id:'pyi15', cat:'python', difficulty:'Easy', title:'Missing Number',
   prompt:'Given nums containing n distinct numbers from 0 to n, find the one missing number.\nExample: [3,0,1] -> 2',
   solution:'def missing_number(nums):\n    n = len(nums)\n    return n * (n + 1) // 2 - sum(nums)',
   explain:'Gauss sum formula for 0..n minus actual sum gives the missing value in O(n) time, O(1) space.'},
  {id:'pyi16', cat:'python', difficulty:'Easy', title:'Majority Element',
   prompt:'Given nums, return the element that appears more than n/2 times. Assume it always exists.\nExample: [2,2,1,1,1,2,2] -> 2',
   solution:'def majority_element(nums):\n    count = 0\n    candidate = None\n    for n in nums:\n        if count == 0:\n            candidate = n\n        count += 1 if n == candidate else -1\n    return candidate',
   explain:"Boyer-Moore voting algorithm — O(1) space, a favorite follow-up after the Counter().most_common(1) answer.",
  },
  {id:'pyi17', cat:'python', difficulty:'Medium', title:'Rotate Array',
   prompt:'Rotate nums to the right by k steps, in-place.\nExample: [1,2,3,4,5,6,7], k=3 -> [5,6,7,1,2,3,4]',
   solution:'def rotate(nums, k):\n    k %= len(nums)\n    nums[:] = nums[-k:] + nums[:-k]',
   explain:'k %= len(nums) handles k larger than the array length — a common edge case interviewers probe for.'},
  {id:'pyi18', cat:'python', difficulty:'Easy', title:'Intersection of Two Arrays',
   prompt:'Given two arrays, return their intersection (unique elements present in both).\nExample: [1,2,2,1], [2,2] -> [2]',
   solution:'def intersection(nums1, nums2):\n    return list(set(nums1) & set(nums2))',
   explain:'Set intersection with & is O(n+m) — mention the sorted two-pointer alternative if arrays are huge.'},
  {id:'pyi19', cat:'python', difficulty:'Easy', title:'First Unique Character',
   prompt:'Given a string s, return the index of the first non-repeating character, or -1 if none exists.\nExample: "leetcode" -> 0',
   solution:'from collections import Counter\ndef first_uniq_char(s):\n    counts = Counter(s)\n    for i, ch in enumerate(s):\n        if counts[ch] == 1:\n            return i\n    return -1',
   explain:'Count everything first, then scan in order — two passes but both O(n).'},
  {id:'pyi20', cat:'python', difficulty:'Easy', title:'Climbing Stairs (DP)',
   prompt:'You can climb 1 or 2 steps at a time. Given n stairs, how many distinct ways to reach the top?\nExample: n=3 -> 3',
   solution:'def climb_stairs(n):\n    a, b = 1, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a',
   explain:'This is just Fibonacci in disguise — ways(n) = ways(n-1) + ways(n-2). Classic intro-to-DP question.'},
  {id:'pyi21', cat:'python', difficulty:'Easy', title:'Merge Two Sorted Lists (as arrays)',
   prompt:'Merge two sorted lists into one sorted list.\nExample: [1,2,4], [1,3,4] -> [1,1,2,3,4,4]',
   solution:'def merge_sorted(a, b):\n    i = j = 0\n    result = []\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            result.append(a[i]); i += 1\n        else:\n            result.append(b[j]); j += 1\n    result.extend(a[i:])\n    result.extend(b[j:])\n    return result',
   explain:'This is the merge step of merge sort — worth knowing cold since it underlies many other problems.'},
  {id:'pyi22', cat:'python', difficulty:'Medium', title:'Maximum Subarray (Kadane\'s)',
   prompt:'Find the contiguous subarray with the largest sum and return that sum.\nExample: [-2,1,-3,4,-1,2,1,-5,4] -> 6 ([4,-1,2,1])',
   solution:'def max_subarray(nums):\n    best = cur = nums[0]\n    for n in nums[1:]:\n        cur = max(n, cur + n)\n        best = max(best, cur)\n    return best',
   explain:"Kadane's algorithm: at each step decide whether to extend the current run or start fresh. O(n).",
  },
  {id:'pyi23', cat:'python', difficulty:'Easy', title:'Find All Duplicates in an Array',
   prompt:'Given nums where 1 <= nums[i] <= n, find all elements that appear twice.\nExample: [4,3,2,7,8,2,3,1] -> [2,3]',
   solution:'from collections import Counter\ndef find_duplicates(nums):\n    return [n for n, c in Counter(nums).items() if c == 2]',
   explain:'Counter-based solution is O(n) time and space; the in-place sign-flipping trick is an O(1)-space follow-up.'},
  {id:'pyi24', cat:'python', difficulty:'Easy', title:'Single Number (XOR)',
   prompt:'Given a list where every element appears twice except one, find that single one, in O(1) space.\nExample: [4,1,2,1,2] -> 4',
   solution:'def single_number(nums):\n    result = 0\n    for n in nums:\n        result ^= n\n    return result',
   explain:'XOR of a number with itself is 0, and XOR is commutative — pairs cancel out, leaving the lone value.'},
  {id:'pyi25', cat:'python', difficulty:'Medium', title:'Implement strStr()',
   prompt:'Given haystack and needle, return the index of the first occurrence of needle in haystack, or -1.\nExample: haystack="hello", needle="ll" -> 2',
   solution:'def str_str(haystack, needle):\n    return haystack.find(needle)',
   explain:"Trivial with .find(), but be ready to implement it manually with a sliding window if asked to avoid built-ins.",
  },
  {id:'pyi26', cat:'python', difficulty:'Easy', title:'Roman to Integer',
   prompt:'Convert a Roman numeral string to an integer.\nExample: "LVIII" -> 58',
   solution:'def roman_to_int(s):\n    vals = {"I":1,"V":5,"X":10,"L":50,"C":100,"D":500,"M":1000}\n    total = 0\n    for i, ch in enumerate(s):\n        v = vals[ch]\n        if i+1 < len(s) and v < vals[s[i+1]]:\n            total -= v\n        else:\n            total += v\n    return total',
   explain:'Subtract when a smaller numeral precedes a larger one (like IV = 4), otherwise add.'},
  {id:'pyi27', cat:'python', difficulty:'Medium', title:'Sort Characters By Frequency',
   prompt:'Given a string, sort its characters by decreasing frequency.\nExample: "tree" -> "eert" or "eetr"',
   solution:'from collections import Counter\ndef frequency_sort(s):\n    counts = Counter(s)\n    return "".join(ch * n for ch, n in counts.most_common())',
   explain:'Counter.most_common() already returns items sorted by frequency descending.'},
  {id:'pyi28', cat:'python', difficulty:'Medium', title:'K Closest Points to Origin',
   prompt:'Given a list of points [x,y] and an integer k, return the k points closest to the origin (0,0).\nExample: points=[[1,3],[-2,2]], k=1 -> [[-2,2]]',
   solution:'def k_closest(points, k):\n    return sorted(points, key=lambda p: p[0]**2 + p[1]**2)[:k]',
   explain:'Sort by squared distance (no need for sqrt) — a heap-based O(n log k) version is the optimized follow-up.'},
  {id:'pyi29', cat:'python', difficulty:'Medium', title:'LRU Cache (simplified)',
   prompt:'Design an LRUCache with get(key) and put(key, value) that evicts the least recently used item when capacity is exceeded.',
   solution:'from collections import OrderedDict\nclass LRUCache:\n    def __init__(self, capacity):\n        self.cache = OrderedDict()\n        self.capacity = capacity\n    def get(self, key):\n        if key not in self.cache:\n            return -1\n        self.cache.move_to_end(key)\n        return self.cache[key]\n    def put(self, key, value):\n        if key in self.cache:\n            self.cache.move_to_end(key)\n        self.cache[key] = value\n        if len(self.cache) > self.capacity:\n            self.cache.popitem(last=False)',
   explain:'OrderedDict gives O(1) move-to-end and pop-first-item, making it perfect for LRU without hand-rolling a linked list.'},
  {id:'pyi30', cat:'python', difficulty:'Medium', title:'Number of Islands (grid DFS)',
   prompt:'Given a 2D grid of "1" (land) and "0" (water), count the number of islands (connected land, 4-directionally).',
   solution:'def num_islands(grid):\n    if not grid: return 0\n    rows, cols = len(grid), len(grid[0])\n    def dfs(r, c):\n        if r<0 or c<0 or r>=rows or c>=cols or grid[r][c] != "1":\n            return\n        grid[r][c] = "0"\n        dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1)\n    count = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == "1":\n                count += 1\n                dfs(r, c)\n    return count',
   explain:'Flood-fill with DFS, marking visited land as water — a very common grid/graph interview pattern.'},
];

const sqlBasics = [
  {id:'sqb1', cat:'sql', difficulty:'Easy', title:'SELECT all columns',
   prompt:'Table employees(id, name, department, salary).\nWrite a query to select all columns and all rows.',
   solution:'SELECT * FROM employees;',
   explain:'* is fine for exploring data, but in production code prefer listing explicit columns.'},
  {id:'sqb2', cat:'sql', difficulty:'Easy', title:'WHERE filter',
   prompt:'Table employees(id, name, department, salary).\nSelect the names of employees earning more than 70000.',
   solution:'SELECT name FROM employees WHERE salary > 70000;',
   explain:'WHERE filters rows before any grouping/aggregation happens.'},
  {id:'sqb3', cat:'sql', difficulty:'Easy', title:'ORDER BY',
   prompt:'Table employees(id, name, department, salary).\nList all employees ordered by salary descending.',
   solution:'SELECT * FROM employees ORDER BY salary DESC;',
   explain:'Default sort order is ASC; DESC must be explicit.'},
  {id:'sqb4', cat:'sql', difficulty:'Easy', title:'LIMIT / Top N',
   prompt:'Table employees(id, name, department, salary).\nReturn the 3 highest-paid employees.',
   solution:'SELECT * FROM employees ORDER BY salary DESC LIMIT 3;',
   explain:'LIMIT after ORDER BY is the standard "top N" pattern (TOP N in SQL Server, ROWNUM in Oracle).'},
  {id:'sqb5', cat:'sql', difficulty:'Easy', title:'DISTINCT',
   prompt:'Table employees(id, name, department, salary).\nList all unique department names.',
   solution:'SELECT DISTINCT department FROM employees;',
   explain:'DISTINCT removes duplicate rows from the result set, applied after SELECT column evaluation.'},
  {id:'sqb6', cat:'sql', difficulty:'Easy', title:'Basic aggregates',
   prompt:'Table employees(id, name, department, salary).\nFind the total number of employees, and the average salary.',
   solution:'SELECT COUNT(*) AS total_employees, AVG(salary) AS avg_salary FROM employees;',
   explain:'COUNT(*) counts rows; COUNT(col) counts non-null values in that column — the distinction matters.'},
  {id:'sqb7', cat:'sql', difficulty:'Easy', title:'GROUP BY',
   prompt:'Table employees(id, name, department, salary).\nFind the average salary per department.',
   solution:'SELECT department, AVG(salary) AS avg_salary\nFROM employees\nGROUP BY department;',
   explain:'Every non-aggregated column in SELECT must appear in GROUP BY.'},
  {id:'sqb8', cat:'sql', difficulty:'Easy', title:'HAVING',
   prompt:'Table employees(id, name, department, salary).\nFind departments with more than 5 employees.',
   solution:'SELECT department, COUNT(*) AS cnt\nFROM employees\nGROUP BY department\nHAVING COUNT(*) > 5;',
   explain:'WHERE filters rows before grouping; HAVING filters groups after aggregation.'},
  {id:'sqb9', cat:'sql', difficulty:'Easy', title:'INNER JOIN',
   prompt:'Tables employees(id, name, dept_id) and departments(id, dept_name).\nList each employee\'s name with their department name.',
   solution:'SELECT e.name, d.dept_name\nFROM employees e\nJOIN departments d ON e.dept_id = d.id;',
   explain:'INNER JOIN only returns rows that have a match in both tables.'},
  {id:'sqb10', cat:'sql', difficulty:'Easy', title:'LEFT JOIN',
   prompt:'Tables employees(id, name, dept_id) and departments(id, dept_name).\nList every employee and their department name, including employees with no department.',
   solution:'SELECT e.name, d.dept_name\nFROM employees e\nLEFT JOIN departments d ON e.dept_id = d.id;',
   explain:'LEFT JOIN keeps every row from the left table; unmatched right-side columns come back NULL.'},
  {id:'sqb11', cat:'sql', difficulty:'Easy', title:'Simple subquery',
   prompt:'Table employees(id, name, department, salary).\nFind employees who earn more than the average salary.',
   solution:'SELECT name FROM employees\nWHERE salary > (SELECT AVG(salary) FROM employees);',
   explain:'A scalar subquery (returns one value) can be used anywhere a single value is expected.'},
  {id:'sqb12', cat:'sql', difficulty:'Easy', title:'IS NULL',
   prompt:'Table employees(id, name, department, manager_id).\nFind employees who have no manager (manager_id is null).',
   solution:'SELECT name FROM employees WHERE manager_id IS NULL;',
   explain:'Never use "= NULL" — NULL comparisons always return unknown, so IS NULL / IS NOT NULL is required.'},
  {id:'sqb13', cat:'sql', difficulty:'Easy', title:'BETWEEN and IN',
   prompt:'Table employees(id, name, department, salary).\nFind employees with salary between 50000 and 80000 who work in "Sales" or "Marketing".',
   solution:'SELECT name FROM employees\nWHERE salary BETWEEN 50000 AND 80000\n  AND department IN (\'Sales\', \'Marketing\');',
   explain:'BETWEEN is inclusive on both ends; IN is shorthand for multiple OR conditions.'},
  {id:'sqb14', cat:'sql', difficulty:'Easy', title:'LIKE pattern match',
   prompt:'Table employees(id, name, department, salary).\nFind employees whose name starts with "A".',
   solution:'SELECT name FROM employees WHERE name LIKE \'A%\';',
   explain:'% matches any sequence of characters, _ matches exactly one character.'},
  {id:'sqb15', cat:'sql', difficulty:'Easy', title:'CASE WHEN',
   prompt:'Table employees(id, name, salary).\nLabel each employee "High" if salary > 100000, "Mid" if > 50000, else "Low".',
   solution:'SELECT name,\n  CASE\n    WHEN salary > 100000 THEN \'High\'\n    WHEN salary > 50000 THEN \'Mid\'\n    ELSE \'Low\'\n  END AS salary_band\nFROM employees;',
   explain:'CASE WHEN evaluates conditions top to bottom and stops at the first match, like if/elif/else.'},
];

const sqlInterview = [
  {id:'sqi1', cat:'sql', difficulty:'Medium', title:'Second Highest Salary',
   prompt:'Table Employee(id, salary).\nWrite a query to return the second highest distinct salary. Return NULL if it doesn\'t exist.',
   solution:'SELECT (\n  SELECT DISTINCT salary FROM Employee\n  ORDER BY salary DESC\n  LIMIT 1 OFFSET 1\n) AS SecondHighestSalary;',
   explain:'Wrapping in a subquery ensures NULL is returned (instead of an empty result) when there is no second value.'},
  {id:'sqi2', cat:'sql', difficulty:'Medium', title:'Nth Highest Salary',
   prompt:'Table Employee(id, salary).\nWrite a query to return the Nth highest distinct salary (N given as a parameter), or NULL if none.',
   solution:'-- Using DENSE_RANK, N = 3 example:\nSELECT salary FROM (\n  SELECT salary, DENSE_RANK() OVER (ORDER BY salary DESC) AS rnk\n  FROM (SELECT DISTINCT salary FROM Employee) t\n) ranked\nWHERE rnk = 3;',
   explain:'DENSE_RANK handles ties correctly (two people tied for #1 both count as rank 1, next distinct salary is rank 2).'},
  {id:'sqi3', cat:'sql', difficulty:'Easy', title:'Duplicate Emails',
   prompt:'Table Person(id, email).\nFind all emails that appear more than once.',
   solution:'SELECT email FROM Person\nGROUP BY email\nHAVING COUNT(*) > 1;',
   explain:'GROUP BY + HAVING is the standard pattern for "find values that repeat."'},
  {id:'sqi4', cat:'sql', difficulty:'Medium', title:'Employees Earning More Than Their Managers',
   prompt:'Table Employee(id, name, salary, managerId).\nFind employees who earn more than their manager.',
   solution:'SELECT e1.name AS Employee\nFROM Employee e1\nJOIN Employee e2 ON e1.managerId = e2.id\nWHERE e1.salary > e2.salary;',
   explain:'Self-join: treat the same table as two roles (employee and manager) via aliases.'},
  {id:'sqi5', cat:'sql', difficulty:'Medium', title:'Department Highest Salary',
   prompt:'Tables Employee(id, name, salary, departmentId), Department(id, name).\nFind the employee(s) with the highest salary in each department.',
   solution:'SELECT d.name AS Department, e.name AS Employee, e.salary\nFROM Employee e\nJOIN Department d ON e.departmentId = d.id\nWHERE e.salary = (\n  SELECT MAX(salary) FROM Employee WHERE departmentId = e.departmentId\n);',
   explain:'Correlated subquery recomputes MAX(salary) per department for each row — handles ties naturally.'},
  {id:'sqi6', cat:'sql', difficulty:'Easy', title:'Rising Temperature',
   prompt:'Table Weather(id, recordDate, temperature).\nFind all dates whose temperature is higher than the previous (calendar) day.',
   solution:'SELECT w1.id\nFROM Weather w1\nJOIN Weather w2 ON w1.recordDate = w2.recordDate + INTERVAL \'1 day\'\nWHERE w1.temperature > w2.temperature;',
   explain:'Self-join on date offset by 1 day is the classic way to compare each row to "yesterday".'},
  {id:'sqi7', cat:'sql', difficulty:'Easy', title:'Combine Two Tables',
   prompt:'Tables Person(personId, firstName, lastName), Address(addressId, personId, city, state).\nReport firstName, lastName, city, state for every person (even if no address exists).',
   solution:'SELECT p.firstName, p.lastName, a.city, a.state\nFROM Person p\nLEFT JOIN Address a ON p.personId = a.personId;',
   explain:'LEFT JOIN from the "must always appear" table (Person) so nobody gets dropped.'},
  {id:'sqi8', cat:'sql', difficulty:'Easy', title:'Customers Who Never Order',
   prompt:'Tables Customers(id, name), Orders(id, customerId).\nFind customers who never placed an order.',
   solution:'SELECT c.name AS Customers\nFROM Customers c\nLEFT JOIN Orders o ON c.id = o.customerId\nWHERE o.id IS NULL;',
   explain:'LEFT JOIN + "WHERE right-side IS NULL" is the standard anti-join pattern.'},
  {id:'sqi9', cat:'sql', difficulty:'Easy', title:'Delete Duplicate Emails',
   prompt:'Table Person(id, email).\nDelete duplicate rows by email, keeping only the one with the smallest id.',
   solution:'DELETE p1 FROM Person p1\nJOIN Person p2\nON p1.email = p2.email AND p1.id > p2.id;',
   explain:'Self-join to find rows that have a "duplicate twin" with a smaller id, then delete those.'},
  {id:'sqi10', cat:'sql', difficulty:'Medium', title:'Rank Scores',
   prompt:'Table Scores(id, score).\nRank scores such that the highest score has rank 1; ties share the same rank and the next rank skips accordingly (like Olympic ranking, i.e. dense rank).',
   solution:'SELECT score,\n  DENSE_RANK() OVER (ORDER BY score DESC) AS "rank"\nFROM Scores;',
   explain:'DENSE_RANK() is exactly the "no gaps after a tie" ranking behavior this question asks for.'},
  {id:'sqi11', cat:'sql', difficulty:'Medium', title:'Consecutive Numbers',
   prompt:'Table Logs(id, num).\nFind all numbers that appear at least 3 times consecutively (by increasing id).',
   solution:'SELECT DISTINCT l1.num AS ConsecutiveNums\nFROM Logs l1\nJOIN Logs l2 ON l1.id = l2.id - 1 AND l1.num = l2.num\nJOIN Logs l3 ON l2.id = l3.id - 1 AND l2.num = l3.num;',
   explain:'Chain three self-joins on consecutive ids — a window-function LAG/LAG(2) version is a cleaner alternative.'},
  {id:'sqi12', cat:'sql', difficulty:'Easy', title:'Employees With Missing Information',
   prompt:'Tables Employees(employee_id, name), Salaries(employee_id, salary).\nFind employee_ids that are missing either a name or a salary record.',
   solution:'SELECT employee_id FROM (\n  SELECT employee_id FROM Employees\n  UNION ALL\n  SELECT employee_id FROM Salaries\n) t\nGROUP BY employee_id\nHAVING COUNT(*) = 1\nORDER BY employee_id;',
   explain:'UNION ALL + GROUP BY count==1 finds ids that appear in only one of the two tables.'},
  {id:'sqi13', cat:'sql', difficulty:'Hard', title:'Trips and Users (Cancellation Rate)',
   prompt:'Tables Trips(id, client_id, driver_id, status, request_at), Users(users_id, banned).\nFor "2013-10-01" to "2013-10-03", find the cancellation rate of trips (status like %cancelled%) for unbanned users, rounded to 2 decimals, grouped by day.',
   solution:'SELECT t.request_at AS Day,\n  ROUND(\n    SUM(CASE WHEN t.status LIKE \'%cancelled%\' THEN 1 ELSE 0 END) * 1.0 / COUNT(*),\n  2) AS "Cancellation Rate"\nFROM Trips t\nJOIN Users cu ON t.client_id = cu.users_id AND cu.banned = \'No\'\nJOIN Users du ON t.driver_id = du.users_id AND du.banned = \'No\'\nWHERE t.request_at BETWEEN \'2013-10-01\' AND \'2013-10-03\'\nGROUP BY t.request_at;',
   explain:'Classic "hard" SQL question: join twice to exclude banned client/driver, then a conditional SUM for the rate.'},
  {id:'sqi14', cat:'sql', difficulty:'Hard', title:'Department Top Three Salaries',
   prompt:'Tables Employee(id, name, salary, departmentId), Department(id, name).\nFind the top 3 distinct salaries in each department.',
   solution:'SELECT d.name AS Department, e.name AS Employee, e.salary AS Salary\nFROM Employee e\nJOIN Department d ON e.departmentId = d.id\nWHERE (\n  SELECT COUNT(DISTINCT e2.salary)\n  FROM Employee e2\n  WHERE e2.departmentId = e.departmentId AND e2.salary > e.salary\n) < 3;',
   explain:'Correlated subquery counts how many distinct salaries beat this one within the department — under 3 means top-3.'},
  {id:'sqi15', cat:'sql', difficulty:'Medium', title:'Exchange Seats',
   prompt:'Table Seat(id, student), ids are consecutive from 1. Swap the names of every pair of adjacent ids (1<->2, 3<->4...); if odd count, the last id keeps its own name.',
   solution:'SELECT\n  CASE\n    WHEN id % 2 = 1 AND id = (SELECT MAX(id) FROM Seat) THEN id\n    WHEN id % 2 = 1 THEN id + 1\n    ELSE id - 1\n  END AS id,\n  student\nFROM Seat\nORDER BY id;',
   explain:'Compute the swapped id with CASE WHEN, handle the odd-count-last-row edge case explicitly, then reorder.'},
  {id:'sqi16', cat:'sql', difficulty:'Medium', title:'Game Play Analysis (First Login)',
   prompt:'Table Activity(player_id, device_id, event_date, games_played).\nFind the first login date for each player.',
   solution:'SELECT player_id, MIN(event_date) AS first_login\nFROM Activity\nGROUP BY player_id;',
   explain:'A simple GROUP BY + MIN — worth knowing since it is often step 1 of a longer, harder question.'},
  {id:'sqi17', cat:'sql', difficulty:'Medium', title:'Cumulative Sum with Window Function',
   prompt:'Table Sales(id, sale_date, amount).\nFor each row, compute a running total of amount ordered by sale_date.',
   solution:'SELECT id, sale_date, amount,\n  SUM(amount) OVER (ORDER BY sale_date) AS running_total\nFROM Sales;',
   explain:'Window functions compute aggregates without collapsing rows — essential for running totals / moving averages.'},
  {id:'sqi18', cat:'sql', difficulty:'Medium', title:'Row Number Per Group',
   prompt:'Table Orders(id, customer_id, order_date, amount).\nFor each customer, number their orders in chronological order (1, 2, 3...).',
   solution:'SELECT id, customer_id, order_date,\n  ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date) AS order_seq\nFROM Orders;',
   explain:'PARTITION BY resets the numbering for each customer_id group — the SQL analogue of a groupby + cumcount.'},
  {id:'sqi19', cat:'sql', difficulty:'Easy', title:'Count Duplicate Rows',
   prompt:'Table Orders(id, customer_id, product, quantity).\nFind (customer_id, product) pairs that have more than one order row.',
   solution:'SELECT customer_id, product, COUNT(*) AS cnt\nFROM Orders\nGROUP BY customer_id, product\nHAVING COUNT(*) > 1;',
   explain:'GROUP BY on multiple columns treats the combination as the "key" for duplicate detection.'},
  {id:'sqi20', cat:'sql', difficulty:'Hard', title:'Median Employee Salary (approx, per department)',
   prompt:'Table Employee(id, name, salary, departmentId).\nFind the median salary in each department (approximate: use PERCENTILE_CONT if available).',
   solution:'SELECT departmentId,\n  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY salary) AS median_salary\nFROM Employee\nGROUP BY departmentId;',
   explain:'PERCENTILE_CONT(0.5) is the standard way to compute a true median in Postgres/Snowflake/BigQuery.'},
  {id:'sqi21', cat:'sql', difficulty:'Medium', title:'Pivot with CASE + SUM',
   prompt:'Table Sales(id, product, quarter, amount) where quarter is \'Q1\'..\'Q4\'.\nPivot so each product is a row and each quarter is a column showing total amount.',
   solution:'SELECT product,\n  SUM(CASE WHEN quarter = \'Q1\' THEN amount ELSE 0 END) AS Q1,\n  SUM(CASE WHEN quarter = \'Q2\' THEN amount ELSE 0 END) AS Q2,\n  SUM(CASE WHEN quarter = \'Q3\' THEN amount ELSE 0 END) AS Q3,\n  SUM(CASE WHEN quarter = \'Q4\' THEN amount ELSE 0 END) AS Q4\nFROM Sales\nGROUP BY product;',
   explain:'CASE WHEN inside SUM() is the portable way to pivot rows into columns without vendor-specific PIVOT syntax.'},
  {id:'sqi22', cat:'sql', difficulty:'Medium', title:'Self Join for Pairs',
   prompt:'Table Friendship(user1, user2, since_date). Friendship is stored one direction only.\nList all pairs of users who both became friends with a third user on the same date (i.e. "friend suggestions").',
   solution:'SELECT f1.user1 AS person_a, f2.user1 AS person_b, f1.user2 AS common_friend\nFROM Friendship f1\nJOIN Friendship f2 ON f1.user2 = f2.user2 AND f1.since_date = f2.since_date AND f1.user1 <> f2.user1;',
   explain:'Self-join on the shared friend + shared date; the inequality guard avoids matching a row with itself.'},
  {id:'sqi23', cat:'sql', difficulty:'Medium', title:'Monthly Active Users',
   prompt:'Table Sessions(user_id, session_date).\nCount distinct active users per calendar month.',
   solution:'SELECT DATE_TRUNC(\'month\', session_date) AS month, COUNT(DISTINCT user_id) AS mau\nFROM Sessions\nGROUP BY DATE_TRUNC(\'month\', session_date)\nORDER BY month;',
   explain:'DATE_TRUNC buckets timestamps into calendar periods — a core metric query pattern in analytics interviews.'},
  {id:'sqi24', cat:'sql', difficulty:'Medium', title:'Percentage of Active Users',
   prompt:'Tables Users(user_id, signup_date), Sessions(user_id, session_date).\nWhat percentage of all signed-up users had at least one session in their signup month?',
   solution:'SELECT ROUND(\n  100.0 * COUNT(DISTINCT s.user_id) / COUNT(DISTINCT u.user_id), 2\n) AS pct_active\nFROM Users u\nLEFT JOIN Sessions s\n  ON u.user_id = s.user_id\n  AND DATE_TRUNC(\'month\', s.session_date) = DATE_TRUNC(\'month\', u.signup_date);',
   explain:'LEFT JOIN with the date condition inside the ON clause (not WHERE) so non-matching users are not dropped from the denominator.'},
  {id:'sqi25', cat:'sql', difficulty:'Hard', title:'Consecutive Login Days (LAG)',
   prompt:'Table Logins(user_id, login_date).\nFind users who logged in on 3 or more consecutive calendar days.',
   solution:'WITH ranked AS (\n  SELECT user_id, login_date,\n    login_date - ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) * INTERVAL \'1 day\' AS grp\n  FROM (SELECT DISTINCT user_id, login_date FROM Logins) d\n)\nSELECT user_id, MIN(login_date) AS streak_start, COUNT(*) AS streak_len\nFROM ranked\nGROUP BY user_id, grp\nHAVING COUNT(*) >= 3;',
   explain:'The "date minus row_number" trick groups consecutive dates into the same bucket (grp) — a well-known streak-finding pattern.'},
  {id:'sqi26', cat:'sql', difficulty:'Medium', title:'Compare with LAG',
   prompt:'Table Stock(id, trade_date, price).\nFor each row, show the price change compared to the previous trade_date.',
   solution:'SELECT id, trade_date, price,\n  price - LAG(price) OVER (ORDER BY trade_date) AS price_change\nFROM Stock;',
   explain:'LAG() looks at the previous row\'s value without a self-join — much cleaner for "compare to prior row" questions.'},
  {id:'sqi27', cat:'sql', difficulty:'Easy', title:'Employee Bonus',
   prompt:'Tables Employee(empId, name, salary, managerId), Bonus(empId, bonus).\nFind employees whose bonus is less than 1000, or who have no bonus record at all.',
   solution:'SELECT e.name, b.bonus\nFROM Employee e\nLEFT JOIN Bonus b ON e.empId = b.empId\nWHERE b.bonus < 1000 OR b.bonus IS NULL;',
   explain:'LEFT JOIN preserves employees with no bonus row; must explicitly OR in the IS NULL check since NULL < 1000 is unknown, not true.'},
  {id:'sqi28', cat:'sql', difficulty:'Easy', title:'Total Sales Per Product',
   prompt:'Table Sales(id, product_id, quantity, price).\nFind total revenue (quantity * price) per product_id, highest revenue first.',
   solution:'SELECT product_id, SUM(quantity * price) AS revenue\nFROM Sales\nGROUP BY product_id\nORDER BY revenue DESC;',
   explain:'Compute the row-level expression (quantity * price) inside the aggregate, then GROUP BY the dimension.'},
  {id:'sqi29', cat:'sql', difficulty:'Medium', title:"First Order Per User",
   prompt:'Table Orders(order_id, user_id, order_date, amount).\nFor each user, return only their first order (earliest order_date).',
   solution:'SELECT o.*\nFROM Orders o\nJOIN (\n  SELECT user_id, MIN(order_date) AS first_date\n  FROM Orders\n  GROUP BY user_id\n) f ON o.user_id = f.user_id AND o.order_date = f.first_date;',
   explain:'Join the table back to a per-group MIN() subquery — a very common "first/last event per entity" pattern. ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY order_date) = 1 is the window-function alternative.'},
  {id:'sqi30', cat:'sql', difficulty:'Hard', title:'Three-Table Join: Order Details',
   prompt:'Tables Customers(id, name), Orders(id, customer_id, order_date), OrderItems(order_id, product_name, price).\nFor each customer, compute total amount spent across all their orders.',
   solution:'SELECT c.name, SUM(oi.price) AS total_spent\nFROM Customers c\nJOIN Orders o ON c.id = o.customer_id\nJOIN OrderItems oi ON o.id = oi.order_id\nGROUP BY c.name\nORDER BY total_spent DESC;',
   explain:'Chaining two JOINs across three tables before aggregating is the norm in real analytics/interview schemas.'},
];

function zip(a, b){
  const out = [];
  const len = Math.max(a.length, b.length);
  for (let i=0;i<len;i++){
    if (i<a.length) out.push(a[i]);
    if (i<b.length) out.push(b[i]);
  }
  return out;
}
function assignDays(list, startDay, endDay){
  const days = endDay - startDay + 1;
  list.forEach((q, i)=>{
    q.day = startDay + Math.floor(i * days / list.length);
    q.phase = q.day <= 14 ? 'basics' : 'interview';
  });
}

const basicsCombined = zip(pythonBasics, sqlBasics);
const interviewCombined = zip(pythonInterview, sqlInterview);
assignDays(basicsCombined, 1, 14);
assignDays(interviewCombined, 15, 32);

const QUESTIONS = [...basicsCombined, ...interviewCombined];
